Add parse function prototypes with anyhow::Error Results
Eathox/expert-system pull request #11
Opened 2021-12-08 19:55 UTC by nanderstabel

In this PR I added the following:
- parser module in which Token, Node and Parser structs are declared
- Several method prototypes that currently cause a "dummy" Error to showcase the anyhow error implementation
- Updated cargo.toml file
- Triggered the Parser code error in the main function
- Added a  "structs" directory with a mod.rs file

2021-12-08 20:09 UTC, nanderstabel commented
Regarding the "get_" methods in the Parser struct.. I'm thinking if maybe it is nicer to make a generic "get()" trait for all the Token variants. Not sure yet if that's possible but I think it would be nice to have.

2021-12-11 23:53 UTC, nanderstabel commented
Pretty content with the current version:
* Error handling is implemented
* I added a bunch of tests
* I got rid of some overcomplex implementation
* The AST building seem to be very solid

You can probably give me some feedback on how I handled the error handling. I will move all the tests to the /tests/ folder later (once your PR is merged). Other feedback is welcome as well (comments maybe?).

2022-02-11 13:07 UTC, Eathox requested changes
I left a couple of questions/notes. I was also wondering what is the purpose of the src/structs hierarchy? What files should be created as part of the src/structs and which shouldn't?

Note: I'm not done yet, about to dissect and review the entirety of the parser. But thought I'd already leave some notes for you.

2022-02-11 13:07 UTC, Eathox commented on src/errors.rs
> +pub const MISSING_IMPLICATOR_ERR: &str = "No implicator found";
~~Consider moving these a `mod errors` inside of src/structs/parser.rs~~
Lets just inline these instead of making a const for each

2022-02-11 13:07 UTC, Eathox commented on src/main.rs
> +    parser.parse("A => B").context("Unable to parse")?;
This isn't really required on the main branch, I think I'd be better if the parser is created but not used.

2022-02-11 13:07 UTC, Eathox commented on src/structs/parser.rs
> +    use crate::Parser;
Prop should be using `use super::*;` instead

2022-02-11 13:07 UTC, Eathox commented on src/structs/parser.rs
> +use crate::errors::*;
I believe `use` is from the perspective of the crate's root so you dont need the `crate::` prefix here

2022-02-11 13:07 UTC, Eathox commented on src/structs/parser.rs
> +    }
I'm not a big fan of big tests functions that check allot of cases, if one of the asserts inside fails it will be harder to track down what exactly is wrong. I'd suggest you make more specific test functions which purely check one case.

Also when doing this you might want to consider checking for a specific error instead of checking if it is any error.

2022-02-11 13:07 UTC, Eathox commented on src/structs/parser.rs
> +impl<'a> Parser {
Fairly generic name that doesn't tell us much of what this does, same goes for the file name

2022-02-11 13:19 UTC, Eathox commented on src/structs/parser.rs
> +        let mut tokenlist: Vec<Token> = Vec::new();
Variable name should be snake_case, eg: `token_list`

2022-02-11 13:22 UTC, Eathox commented on src/structs/parser.rs
> +        let tokenlist = self.tokenize(input).context(TOKENIZATION_ERR)?;
Variable name should be snake_case, eg: `token_list`

2022-03-24 10:31 UTC, nanderstabel commented
Closing this pull request. 

Developments in the [truthtable](https://github.com/Eathox/expert-system/tree/truthtable) branch drastically alter (and simplify) the implementation in this pull request.

2022-03-24 10:31 UTC, closed without merging